# Generated by Django 3.1.1 on 2020-10-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('directory', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=600)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forager_server_api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_function', models.CharField(max_length=300)),
                ('label_type', models.CharField(max_length=300)),
                ('label', models.CharField(max_length=300)),
                ('dataset_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forager_server_api.datasetitem')),
            ],
        ),
    ]
